version: '3.5'
services:
  api1: # API - Instância 01
    image: marcusadriano/rinhabackend-go:latest
    hostname: api1
    depends_on:
      - db
    expose:
      - "8080"
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=postgres://postgres:mysecretpassword@db:5432/rinhabackend?pool_max_conns=20&pool_min_conns=10&pool_max_conn_lifetime=60s
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '250MB'

  api2: # API - Instância 02
    image: marcusadriano/rinhabackend-go:latest
    hostname: api2
    depends_on:
      - db
    expose:
      - "8080"
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=postgres://postgres:mysecretpassword@db:5432/rinhabackend?pool_max_conns=20&pool_min_conns=10&pool_max_conn_lifetime=60s
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '250MB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - db
      - api1
      - api2
    expose:
      - "9999"
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '1GB'

  db: # Banco de dados
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=rinhabackend
    expose:
      - "5432"
    ports:
      - 5432:5432
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: postgres -c 'config_file=/etc/postgresql/postgresql.conf'
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1250MB'