// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package postgres

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Pessoa struct {
	ID         uuid.UUID
	Nome       string
	Apelido    string
	Stack      pgtype.Text
	Nascimento pgtype.Date
}
